# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-and-test-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: install vcpkg and dependencies
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgFormatString: |
            ["install", "gtest"]
          vcpkgGitCommitId: ef7dbf94b9198bc58f45951adcf1f041fcbc5ea0

      - name: set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: build test
        run: |
          cl /std:c++20 /Iinclude /I"${VCPKG_ROOT}\installed\x64-windows\include" /Fe:test.exe tests\test.cpp /link /LIBPATH:"${VCPKG_ROOT}\installed\x64-windows\lib" gtest.lib gtest_main.lib

      - name: run test
        run: .\test.exe
